global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spark_master'
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['172.18.0.10:8080']

  - job_name: 'spark_driver'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['172.18.0.10:4040', 'localhost:4041']

  - job_name: 'spark_workers'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['172.18.0.2:8080', '172.18.0.3:8080']

  - job_name: 'spark_executors'
    metrics_path: '/metrics/executors/prometheus'
    static_configs:
      - targets: ['172.18.0.10:4040', 'localhost:4041']
